services:
  pg:
    image: postgres:16.6
    networks:
      - app-network
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
    environment:
      DB_CONNECTION: pgsql
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: studs
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    env_file:
      - .env

  payara-service:
    build:
      context: .
      dockerfile: Dockerfile.payara-service
    environment:
      - PAYARA_ARGS=--log-level FINEST
    depends_on:
      - pg
      # - kafka
    networks:
      - app-network
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio_data:/data
      - ./config:/root/.minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template.prod:/etc/nginx/templates/default.conf.template:ro
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

  spring:
    build:
      context: .
      dockerfile: Dockerfile.file-service
    depends_on:
      # - kafka
      - minio
      - pg
    networks:
      - app-network
    env_file:
      - .env

volumes:
  pg-data:
  minio_data:

networks:
  app-network:
    driver: bridge
