spring:
  application:
    name: fileService
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          sharedCache:
            mode: ENABLE_SELECTIVE
          region:
            factory_class: infinispan
          infinispan:
            cfg: org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
logging:
  level:
    org.springframework: INFO
