spring:
  application:
    name: fileService
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        cache:
          default_cache_concurrency_strategy: READ_WRITE
          use_second_level_cache: true
          use_query_cache: true
          sharedCache:
            mode: ALL
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

logging:
  level:
    org.springframework: INFO
    org.hibernate.cache: DEBUG
