services:
  pg:
    image: postgres:16.6
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
    environment:
      DB_CONNECTION: pgsql
      POSTGRES_HOST: localhost
      POSTGRES_DB: studs
      PGDATA: /var/lib/postgresql/data/pgdata

    env_file:
      - ../.env

volumes:
  pg-data:
